name: gpchat #changing it will force you to change appname in import statement inside every .dart file.
description: Chats & Calling app

version: 3.0.2-beta+8
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^4.0.7
  async: ^2.8.1
  audioplayers: ^0.20.1
  cached_network_image: ^3.1.0
  chewie: ^1.2.2
  cloud_firestore: ^2.5.2
  cloud_functions: ^3.0.3
  collection: ^1.15.0-nullsafety.4
  connectivity: ^3.0.6
  contacts_service: ^0.6.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  data_connection_checker_tv: ^0.3.5-nullsafety
  device_info: ^2.0.2
  devicelocale: ^0.4.2
  diacritic: ^0.1.3
  dio: ^4.0.0
  dotted_border: ^2.0.0+1
  emoji_picker_flutter: ^1.0.7
  encrypt: ^5.0.1
  file_picker: ^4.0.2
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.3.0
  firebase_messaging: ^11.1.0
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.0-nullsafety
  flutter_colorpicker: ^0.6.0
  flutter_image_compress: ^1.1.0
  flutter_link_previewer: ^2.6.1
  flutter_linkify: ^5.0.2
  flutter_local_notifications: ^8.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_secure_storage: ^5.0.2
  flutter_sound: ^8.3.12
  flutter_video_info: ^1.2.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.1.0
  geolocator: ^7.6.0
  giphy_get: ^3.0.1
  google_mobile_ads: ^0.13.5
  group_button: ^3.1.0
  html: ^0.15.0
  http: ^0.13.3
  http_auth: ^1.0.1
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  jiffy: ^4.1.0
  launch_review: ^3.0.1
  link_preview_generator: ^1.2.0
  local_auth: ^1.1.7
  localstorage: ^4.0.0+1
  media_info: ^0.8.0
  mime: ^1.0.1
  ntp: ^2.0.0
  overlay_support: ^1.2.1
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.3
  percent_indicator: ^3.0.1
  permission_handler: ^8.1.6
  photo_view: ^0.12.0
  provider: ^6.0.0
  random_string: ^2.3.1
  receive_sharing_intent: ^1.4.5
  scoped_model: ^2.0.0-nullsafety.0
  share: ^2.0.4
  shared_preferences: ^2.0.8
  sms_autofill: ^2.1.2
  story_view: ^0.13.1
  string_validator: ^0.3.0
  translator: ^0.1.7
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.10
  video_compress:
    git:
      url: https://github.com/jonataslaw/videoCompress.git
      ref: a14d392
  video_player: ^2.2.0
  video_thumbnail: ^0.4.3
  wakelock: ^0.5.6
dependency_overrides:
  provider: ^6.0.0 # for chewie 1.2.2
dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_driver:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  test: ^1.16.8
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    - assets/flags/
    - lib/Services/localization/json_languages/
